import pic from '../images/s1.jpg';



const Item = [
    {
      id: 1,
      product_name: "Hangover stew",
      description: "Korean Foods",
      price: 350,
      currency: "Rs",
      thumb:pic,
    },
    {
      id: 2,
      product_name: "Soft Tofu Stew ",
      description: "Korean Foods",
      price: 250,
      currency: "Rs",
      thumb: pic,
    },
    {
      id: 3,
      product_name: "Samgyeopsal",
      description: "Korean Foods",
      price: 350,
      currency: "RS",
      thumb: pic,
    },
  
    {
      id: 4,
      product_name: "Chimaek",
      description: "Korean Foods",
      price: 600,
      currency: "Rs",
      thumb: pic,
    },
    {
      id: 5,
      product_name: "Kimchi Stew",
      description: "Korean Foods",
      price: 1250,
      currency: "Rs",
      thumb: pic,
    },
    {
      id: 6,
      product_name: "Instant noodles",
      description: "Chinese Foods",
      price: 499,
      currency: "Rs",
      thumb: pic,
    },
    {
      id: 7,
      product_name: "RBraised Pork Balls in Gravy",
      description: "Chinese Foods",
      price: 699,
      currency: "Rs",
      thumb: pic,
    },
    {
      id: 8,
      product_name: "Dumplings",
      description: "Chinese Foods",
      price: 299,
      currency: "Rs",
      thumb: pic,
    },
    {
      id: 9,
      product_name: "Steamed momos",
      description: "Chinese Foods",
      price: 1499,
      currency: "RS",
      thumb: pic,
    },
    {
      id: 10,
      product_name: "Steamed momos",
      description: "Chinese Foods",
      price: 1999,
      currency: "RS",
      thumb: pic,
    },
    {
      id: 11,
      product_name: "Steamed momos",
      description: "Chinese Foods",
      price: 999,
      currency: "RS",
      thumb: pic,
    },
    {
      id: 12,
      product_name: "Steamed momos",
      description: "Chinese Foods",
      price: 890,
      currency: "RS",
      thumb: pic,
    },
    {
      id: 13,
      product_name: "Steamed momos",
      description: "Chinese Foods",
      price: 400,
      currency: "RS",
      thumb:pic,
    },
    {
      id: 14,
      product_name: "Steamed momos",
      description: "Chinese Foods",
      price: 250,
      currency: "RS",
      thumb: pic,
    },
    {
      id: 15,
      product_name: "Steamed momos",
      description: "Chinese Foods",
      price: 150,
      currency: "RS",
      thumb:pic,
    },
  ];
  export default Item;