export const Data = [
  {
    id: 1,
    img: "foodimage/chi1.jpg",
    title: "Khans",
    price: "500",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },

  {
    id: 2,
    img: "foodimage/chi1.jpg",
    title: "Javed",
    price: "999",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },

  {
    id: 3,
    img: "foodimage/chi1.jpg",
    title: "Vintage Machine",
    price: "699",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },

  {
    id: 4,
    img: "foodimage/chi1.jpg",
    title: "Grill Mexican",
    price: "999",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },

  {
    id: 5,
    img: "foodimage/chi1.jpg",
    title: "Brown Cakes",
    price: "450",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },

  {
    id: 6,
    img: "foodimage/chi1.jpg",
    title: "Spago",
    price: "67",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },

  {
    id: 7,
    img: "foodimage/chi1.jpg",
    title: "Bake with cake",
    price: "23",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },

  {
    id: 8,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 9,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 10,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 11,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 12,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 13,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 14,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 15,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 16,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 17,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 18,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 19,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 20,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 21,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 22,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 23,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
  {
    id: 24,
    img: "foodimage/chi1.jpg",
    title: "The Lady & Sons",
    price: "250",
    details: "⭐⭐⭐⭐⭐",
    count: 1,
    isInCart: false,
  },
];
